name: 'Parse label'

on:
  pull_request:
    types: [labeled]

env:
  IS_MAJOR: >-
      ${{ contains( github.event.pull_request.labels.*.name, 'bumpversion/major' ) }}
  IS_MINOR: >-
      ${{ contains( github.event.pull_request.labels.*.name, 'bumpversion/minor' ) }}
  IS_PATCH: >-
      ${{ contains( github.event.pull_request.labels.*.name, 'bumpversion/patch' ) }}
  PR_NUMBER: ${{ github.event.pull_request.number }}
  PR_TITLE: ${{ github.event.pull_request.title }}
  GITHUB_HEAD_REF: ${{ github.head_ref }}

jobs:
  make_artifact:
    if: >-
      (
        contains( github.event.pull_request.labels.*.name, 'bumpversion/major' ) ||
        contains( github.event.pull_request.labels.*.name, 'bumpversion/minor' ) ||
        contains( github.event.pull_request.labels.*.name, 'bumpversion/patch' )
      ) && (
        github.event.sender.login == 'andrzejnovak'
      )
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Milestone it
      uses: iyu/actions-milestone@v1
      with:
        repo-token: "${{ secrets.TOKEN }}"
        configuration-path: .github/milestone.yml
    - name: Determine version part
      run: |
        if [ $IS_MAJOR == 'true' ]
        then
          echo "::set-env name=BV_PART::major"
        elif [ $IS_MINOR == 'true' ]
        then
          echo "::set-env name=BV_PART::minor"
        else
          echo "::set-env name=BV_PART::patch"
        fi

    - name: Generate artifact
      run: |
        mkdir -p artifacts
        cat > artifacts/message.md <<EOF
        {
          "BV_PART": "${BV_PART}",
          "PR_TITLE": "${PR_TITLE}",
          "PR_NUMBER": "${PR_NUMBER}"
        }
        
        EOF
    - name: Store artifact
      uses: actions/upload-artifact@v1
      with:
        name: message
        path: artifacts

    - name: 'Create new milestone'
      id: createmilestone
      uses: "WyriHaximus/github-action-create-milestone@master"
      with:
        title: "DUMMY"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"